networks:
  harbr:
    driver: bridge

services:
  frontend:
    image: ghcr.io/harbr-foundation/harbr-ui:main
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://api:3030
      - DATABASE_URL=./harbr.db
      - JWT_SECRET=${JWT_SECRET:-default_secret_for_development}
      - HOST=0.0.0.0
    expose:
      - "4173"
    depends_on:
      - api
    networks:
      - harbr

  router:
    image: ghcr.io/harbr-foundation/harbr-router:main
    ports:
      - "8080:8080"
    volumes:
      - ./proxy-config.yml:/etc/harbr-router/config.yml
    restart: unless-stopped
    networks:
      - harbr

  api:
    image: ghcr.io/harbr-foundation/harbr:main
    environment:
      RUST_LOG: info
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/harbr
      CORS_ORIGIN: http://localhost:3030
    expose:
      - "3030"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - harbr

  db:
    image: mysql:8.2
    restart: always
    environment:
      - MYSQL_DATABASE=harbr
      - MYSQL_ROOT_PASSWORD=harbr
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=harbr"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - harbr

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt